apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: "ew0KCSJhdXRocyI6IHsNCgkJImdoY3IuaW8iOiB7DQoJCQkiYXV0aCI6ICJaRzFwZEhKcGVYTndaV3hwZVRwbmFIQmZUMFZGTmpaNk9EZHVhbmxFVmpoRllUVnRWbGxLYkhnemRXcFpPRGxuTTJaelIzQjYiDQoJCX0NCgl9LA0KCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLA0KCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4IiwNCgkicGx1Z2lucyI6IHsNCgkJIi14LWNsaS1oaW50cyI6IHsNCgkJCSJlbmFibGVkIjogInRydWUiDQoJCX0NCgl9LA0KCSJmZWF0dXJlcyI6IHsNCgkJImhvb2tzIjogInRydWUiDQoJfQ0KfQ=="
type: kubernetes.io/dockerconfigjson
